export {
  getHealthCheckQueryKey,
  getListVehiclesQueryKey,
  getGetVehicleQueryKey,
  getGetVehicleHistoryQueryKey,
  getGetVehicleRemindersQueryKey,
  getListServiceCentersQueryKey,
  getGetServiceCenterQueryKey,
  getListMechanicsForCenterQueryKey,
  getGetMechanicQueryKey,
  getListBookingsQueryKey,
  getGetBookingQueryKey,
  getGetInvoiceQueryKey,
  getGetOwnerDashboardQueryKey,
  getGetCenterDashboardQueryKey,
  getListActivityQueryKey,
  getListServiceTypesQueryKey,
  getListVendorsQueryKey,
  getGetVendorQueryKey,
  getListPartsQueryKey,
  getGetPartQueryKey,
  getListPartsForVendorQueryKey,
  getListPartCategoriesQueryKey,
  getListOrdersQueryKey,
  getGetOrderQueryKey,
  getGetVendorDashboardQueryKey,
} from "@workspace/api-client-react";
