export const SERVICE_TYPES = [
  {
    id: "oil-change",
    name: "Oil Change",
    description: "Drain old oil, replace filter, refill with manufacturer-grade oil.",
    estimatedHours: 1,
    startingPrice: 45,
    icon: "droplet",
  },
  {
    id: "brake-service",
    name: "Brake Service",
    description: "Inspect pads, rotors, and fluid. Replace pads if worn beyond spec.",
    estimatedHours: 2,
    startingPrice: 120,
    icon: "disc",
  },
  {
    id: "engine-diagnostics",
    name: "Engine Diagnostics",
    description: "OBD-II scan, root-cause analysis, written report with recommended fixes.",
    estimatedHours: 1.5,
    startingPrice: 80,
    icon: "activity",
  },
  {
    id: "ac-repair",
    name: "AC Repair",
    description: "Refrigerant check, leak test, compressor diagnostics and recharge.",
    estimatedHours: 2,
    startingPrice: 150,
    icon: "wind",
  },
  {
    id: "tire-rotation",
    name: "Tire Rotation & Balance",
    description: "Rotate tires by manufacturer pattern and balance each wheel.",
    estimatedHours: 1,
    startingPrice: 60,
    icon: "circle",
  },
  {
    id: "battery-check",
    name: "Battery Service",
    description: "Load test, clean terminals, replace battery if necessary.",
    estimatedHours: 0.5,
    startingPrice: 40,
    icon: "battery",
  },
  {
    id: "full-inspection",
    name: "Full Vehicle Inspection",
    description: "100-point inspection covering safety, drivetrain, electrical, and body.",
    estimatedHours: 2,
    startingPrice: 95,
    icon: "clipboard-check",
  },
  {
    id: "transmission-service",
    name: "Transmission Service",
    description: "Fluid drain and refill, filter replacement, gearbox health check.",
    estimatedHours: 3,
    startingPrice: 220,
    icon: "settings",
  },
] as const;
