const colors = {
  light: {
    text: "#21252d",
    tint: "#f26a0d",
    background: "#faf8f4",
    foreground: "#21252d",
    card: "#ffffff",
    cardForeground: "#21252d",
    primary: "#f26a0d",
    primaryForeground: "#ffffff",
    secondary: "#3d5a66",
    secondaryForeground: "#ffffff",
    muted: "#ebe6df",
    mutedForeground: "#5c6471",
    accent: "#e9e2d6",
    accentForeground: "#21252d",
    destructive: "#c92020",
    destructiveForeground: "#ffffff",
    border: "#ddd6cb",
    input: "#ddd6cb",
    success: "#2f7a39",
    warning: "#c87a0c",
  },
  dark: {
    text: "#f5f0e7",
    tint: "#f57c2a",
    background: "#161a20",
    foreground: "#f5f0e7",
    card: "#1d2229",
    cardForeground: "#f5f0e7",
    primary: "#f57c2a",
    primaryForeground: "#ffffff",
    secondary: "#527a89",
    secondaryForeground: "#ffffff",
    muted: "#2c333e",
    mutedForeground: "#b8b3a6",
    accent: "#2c333e",
    accentForeground: "#f5f0e7",
    destructive: "#d93b3b",
    destructiveForeground: "#ffffff",
    border: "#2c333e",
    input: "#2c333e",
    success: "#5fae6a",
    warning: "#e0a23a",
  },
  radius: 6,
};

export default colors;
